server.port=8081
spring.application.name=pizza-hamburguer

# Format: jdbc:postgresql://[host]:[port]/[database_name]
spring.datasource.url=jdbc:postgresql://localhost:5432/orders

spring.datasource.username=orders
spring.datasource.password=orders

# 3. Driver Class Name
# spring.datasource.driver-class-name=org.postgresql.Driver

# careful, this updates the ddl automatically based on the Entities schema
spring.jpa.hibernate.ddl-auto=update

# debugging : sql logging in terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true